#!/bin/bash

cd /c/core/_"$1"/ >/dev/null 2>&1;

if [ "$2" != "" ];
then   
  if cd ./courses/"$2" >/dev/null 2>&1;
  then
  elif cd ./courses/comp"$2" >/dev/null 2>&1;
  then 
  elif cd ./courses/seng"$2" >/dev/null 2>&1;
  then
  elif cd ./courses/math"$2" >/dev/null 2>&1;
  then
  else
   echo "Failed to goto directory @ $1 -> $2"
  fi
fi 
