#!/bin/sh

if [ "$#" -eq 0 ]; 
then
  cd ~/corelx
else 
  currpath=~/corelx/_"$1"
  cd ~/corelx/_"$1"/ >/dev/null 2>&1;

  argv=("$@")
  for i in {2.."$#"}
  do
    if [ -d "${currpath}" ]; then
      currpath="${currpath}/${argv[i]}"
    fi

    x="${i}"
  done

  #echo "${currpath}"

  if [ "$1" = "uni" ];
  then   
    if cd ./"$2" >/dev/null 2>&1; then
    elif cd ./comp"$2" >/dev/null 2>&1; then 
    elif cd ./seng"$2" >/dev/null 2>&1; then
    elif cd ./math"$2" >/dev/null 2>&1; then
    else
      echo -e "${Red} »» "$2" is not a valid course."
    fi
  else
    if [ -d "${currpath}" ]; then
      cd "${currpath}"
    fi
  fi
fi
