#!/bin/bash

echo -e "${Blue} »» Preparing and pushing scripts to git...${Yellow}"
cp ~/.zshrc ~/corelx/_scripts
cd  ~/corelx/_scripts
git add .
git commit -m "[**Auto commit**]"
git push

if [ $? -eq 0 ]; then
  echo -e "${Green} »» Pushed to 'autoscripts' repo."
else
  echo -e "${Red} »» Failed to push; check output for details."
fi
