#!/bin/bash

echo -e "${Blue} »» Preparing and pushing scripts to git...${Yellow}"
cp ~/.zshrc /c/core/_scripts/
cd /c/core/_scripts
git add .
git commit -m "updating scripts"
git push
echo -e "${Green} »» Pushed to 'autoscripts' repo."