#!/bin/bash

echo -e "${Blue} »» Preparing and pushing scripts to git...${Yellow}"
cp ~/.zshrc /c/core/_scripts/
cd /c/core/_scripts
git add .
git commit -m "updating scripts"
git push

if [ $? -eq 0 ]; then
  echo -e "${Green} »» Pushed to 'autoscripts' repo."
else
  echo -e "${Red} »» Failed to push; check output for details."
fi
