#!/bin/bash
zid="z5209948"
folder="~/code/"

if [ "$#" -lt 2 ];
then
  echo -e "${Yellow} »» Usage: zcp <file1, file2, ...> <remote-folder/../>"
  exit
fi

echo -e "${Blue} »» Moving ${@:1:$#-1} to remote ${folder}${!#}${Yellow}"
scp "${@:1:$#-1}" "${zid}@cse.unsw.edu.au:${folder}${!#}"

if [ $? -eq 0 ]; then
  echo -e "${Green} »» Moved files to UNSW servers successfully."
else
  echo -e "${Red} »» Failed to move files; check output for details."
fi
